"""empty message

Revision ID: c2a0398fece7
Revises: d48b6aafcc1e
Create Date: 2016-09-23 19:02:28.477231

"""

# revision identifiers, used by Alembic.
revision = 'c2a0398fece7'
down_revision = 'd48b6aafcc1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_item',
    sa.Column('from_item_id', sa.Integer(), nullable=False),
    sa.Column('dest_item_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dest_item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['from_item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('from_item_id', 'dest_item_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_item')
    ### end Alembic commands ###
